# Site settings
title: x64dbg
description: "An open-source x64/x32 debugger for windows."
baseurl: ""
url: "https://www.x64dbg.com"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
